Traceback (most recent call last):
  File "run.py", line 57, in <module>
    tnvmc.run(start,stop,tmpdir=tmpdir)
  File "/home/rppeng/code/quimb-refactor/quimb/tensor/vmc.py", line 162, in run
    self.sample()
  File "/home/rppeng/code/quimb-refactor/quimb/tensor/vmc.py", line 193, in sample
    self._sample_stochastic(compute_v=compute_v,compute_Hv=compute_Hv)
  File "/home/rppeng/code/quimb-refactor/quimb/tensor/vmc.py", line 241, in _sample_stochastic
    raise ValueError(f'RANK={RANK},config={config},cx={cx},ex={ex}')
ValueError: RANK=29,config=(2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 0, 1, 2, 0),cx=2.452811645790744e-07,ex=-9.712744090454159
slurmstepd: error: *** JOB 484268 ON pauling028 CANCELLED AT 2023-05-03T23:40:26 ***
mpirun: abort is already in progress...hit ctrl-c again to forcibly terminate

mpirun: Forwarding signal 18 to job
